# Test your FastAPI endpoints

POST http://localhost:8000/players/%23Y0RGQGQY2/refresh
Accept: application/json

###

GET http://localhost:8000/players/%23Y0RGQGQY2/analysis
Accept: application/json

###
